version: "3.3"

services:
  node:
    container_name: node_container
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./:/var/www/html
  php-fpm:
    container_name: php_container
    build:
      context: .
      dockerfile: DockerfilePHP-FPM
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html
      - ./config/php.ini-production:/usr/local/etc/php/php.ini
    restart: always
  postgres:
    env_file: .env.local
    container_name: postgres_container
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    env_file: .env.local
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
